apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- https://github.com/argoproj-labs/argocd-agent/install/kubernetes/agent?ref=v0.5.3
- ns.yaml
- app.yaml
- argocd-agent-ca.yaml
- argocd-agent-client-tls.yaml

helmCharts:
- name: argo-cd
  releaseName: argocd
  namespace: argocd
  version: 8.5.8
  includeCRDs: true
  repo: https://argoproj.github.io/argo-helm
  valuesInline:
    # disable dex
    dex:
      enabled: false
    # disable server
    server:
      replicas: 0
    # disable notifications controller
    notifications:
      enabled: false
    configs:
      cm:
        kustomize.buildOptions: "--enable-helm"
      secret:
        extra:
          server.secretkey: "Y2k4eFpYQ09UajBmMFhReGJHT3p2aXliTWMyRm9PQWsK"

# Update the agent configuration to connect to your principal using mTLS authentication:
configMapGenerator:
- name: argocd-agent-params
  behavior: merge
  literals:
  - agent.server.port=443
  - agent.mode=autonomous
  - agent.creds=mtls:any
  - agent.server.address=principal.markyoung.us

patches:
- target:
    kind: Secret
    name: argocd-agent-principal-userpass
  patch: |
    $patch: delete
    apiVersion: v1
    kind: Secret
    metadata:
      name: argocd-agent-principal-userpass
- target:
    kind: Secret
    name: argocd-notifications-secret
  patch: |
    $patch: delete
    apiVersion: v1
    kind: Secret
    metadata:
      name: argocd-notifications-secret
