apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd-principal

resources:
- ns.yaml
- ca.yaml
- https://github.com/argoproj-labs/argocd-agent/install/kubernetes/principal?ref=v0.4.1
- cert-manager.yaml
- agent-principal.yaml

helmCharts:
- name: argo-cd
  releaseName: argocd
  namespace: argocd-principal
  version: 8.5.8
  includeCRDs: true
  repo: https://argoproj.github.io/argo-helm
  valuesInline:
    applicationSet:
      replicas: 0
    controller:
      replicas: 0
    server:
      service:
        type: LoadBalancer
    configs:
      cm:
        kustomize.buildOptions: "--enable-helm"
      params:
        application.namespaces: "*"
      secret:
        argocdServerAdminPassword: "$2a$10$rbH6NowmeCKkkXg.hMAcAeTDG3.YUYqzlGBDrHbRJTK.xSkZ.rxQG"
        extra:
          server.secretkey: "Y2k4eFpYQ09UajBmMFhReGJHT3p2aXliTWMyRm9PQWsK"

configMapGenerator:
- name: argocd-agent-params
  behavior: merge
  literals:
  - principal.namespace=argocd-principal

patches:
- target:
    kind: Secret
    name: argocd-agent-principal-userpass
  patch: |
    $patch: delete
    apiVersion: v1
    kind: Secret
    metadata:
      name: argocd-agent-principal-userpass
- target:
    kind: Secret
    name: argocd-notifications-secret
  patch: |
    $patch: delete
    apiVersion: v1
    kind: Secret
    metadata:
      name: argocd-notifications-secret
